flags:
  model-json-js:
    paths: 
      - packages/model-json-js/src/
  schema-json-js:
    paths:
      - packages/schema-json-js/src/

coverage:
  status:
    changes: off
    patch: off
    project:
      default:
        target: 90%
        threshold: 0%
      model-json-js:
        target: 90%
        threshold: 0%
        flags:
          - model-json-js
      schema-json-js:
        target: 90%
        threshold: 0%
        flags:
          - schema-json-js
