version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/model-json-js
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/model-json-js

  install_dependencies:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/model-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install --no-optional
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/model-json-js/node_modules

  test:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/model-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run lint and unit tests
          command: npm run test:all && npm test
      - run:
          name: Run coverage report
          command: npm run coverage
      - store_test_results:
          path: ~/model-json-js/coverage.lcov
      - store_artifacts:
          path: ~/model-json-js/coverage.lcov

  browserstack:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/model-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run BrowserStack tests
          command: npm run browserstack

  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/model-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build and compress code
          command: npm run build && node ./bin/compress
      - save_cache:
          key: assets-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/model-json-js/package.tar.gz
      - store_artifacts:
          path: ~/model-json-js/package.tar.gz

workflows:
  version: 2
  code-review:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      # - browserstack:
      #     requires:
      #       - test
      - build:
          requires:
            - test
